name: Run Tests # The workflow name you see in github actions tab.
# Trigger workflow on push to main
on: [push] # event
jobs:
  hello: # job name
    runs-on: ubuntu-latest #where to run
    steps:
      - name: Print Hello World
        run: echo "Hello, World! 001"