name: Run Tests # The workflow name you see in github actions tab.
# Trigger workflow on push to main
on: [push] # event
jobs:
  hello:
    run-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"