name: My First workflow # Workflow name
on: push # trigger event
jobs: # work to perform
  build:
    runs-on: ubuntu-latest # OS machine
    steps: # command/ actions
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello World"


---
name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say hai
        run: echo "HAI"