name: Test1
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello"
        
---
name: Test2
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say hai
        run: echo "Hai"
