# name: Environment Selector workflow
# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: "Select Environment"
#         required: true
#         default: QA
#         type: choice
#         options:
#         - DEV
#         - PROD
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Show selected env
#         run: echo "Deployment to ${{ github.event.inputs.environment}}"

name: Test Env
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Env"
        required: true
        type: choice
        options:
          - PROD
          - DEV
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Test Server
        run: echo "It is Successful ${{github.event.inputs.environment }}"